language: clojure
dist: trusty
lein: 2.9.0
jdk: openjdk12
sudo: false
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - lein do clean, cljfmt check, test
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
